create table Roles (
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(30) unique
);

create table Addresses (
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
street varchar(50),
number varchar(10),
zip_code varchar(6),
city varchar(30)
);

create table Users (
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(30),
surname varchar(30)
);

create table Orders (
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

create table Products (
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(30) unique,
type varchar(30)
);

create table Products2Orders (
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

ALTER TABLE Users ADD CONSTRAINT role FOREIGN KEY (role) REFERENCES Roles(id) ON DELETE CASCADE
ALTER TABLE Users ADD CONSTRAINT address FOREIGN KEY (address) REFERENCES Addresses(id) ON DELETE CASCADE

ALTER TABLE Orders ADD CONSTRAINT users FOREIGN KEY (users) REFERENCES Users(id) ON DELETE CASCADE
ALTER TABLE Orders ADD CONSTRAINT address FOREIGN KEY (address) REFERENCES Addresses(id) ON DELETE CASCADE

ALTER TABLE Products2Orders ADD CONSTRAINT product FOREIGN KEY (product) REFERENCES Products(id) ON DELETE CASCADE
ALTER TABLE Products2Orders ADD CONSTRAINT orders FOREIGN KEY (orders) REFERENCES Orders(id) ON DELETE CASCADE